spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE} # Placeholder for active profile (set using environment variable)
  flyway:
    locations: classpath:db/migration  # Flyway migration scripts location
  r2dbc:
    url: r2dbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:Quiz}
    username: postgres  # Use environment variable for username
    password: Varun@008  # Use environment variable for password
    driver: io.r2dbc.postgresql.PostgresqlConnection
  pool:
    enabled: true
    max-size: 5
    max-idle-time: 15m
    initial-size: 5
    validation-query: SELECT 1

